version: '3'
services:
  etcd:
    build: ./etcd
    hostname: etcd
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - etcd

  nextbus:
    build: ./nextbus
    ports:
      - "5000"
    depends_on:
      - nginx

  nextbus1:
    build: ./nextbus
    ports:
      - "5000"
    depends_on:
      - nginx

  redis:
    image: redis
    ports:
      - "6379"

