#!/bin/bash
set -eo pipefail

ETCD=http://etcd:2379

echo "[INFO] Booting Nginx container..."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/nginx.toml; do
	echo "[WARNING] confd is still busy waiting for etcd..."
	sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/nginx.toml &
echo "[INFO] Nginx configuration is ready. confd is watching every 10 seconds..."

# Start the Nginx service using the generated config
echo "[INFO] Starting Nginx..."
service nginx start

